'use client';

import { motion } from 'framer-motion';
import Image from 'next/image';
import type { IPSSummary } from '@/types/ips';
import type { RelationshipManager } from '@/types/rm';

interface Props {
  summary: IPSSummary;
  rm: RelationshipManager;
  investorName: string;
}

const riskColors: Record<string, { bg: string; text: string; border: string }> = {
  'Conservative':        { bg: 'bg-blue-50',   text: 'text-blue-700',         border: 'border-blue-200'  },
  'Moderate':            { bg: 'bg-status-green-bg', text: 'text-status-green', border: 'border-green-200' },
  'Moderate-Aggressive': { bg: 'bg-status-amber-bg', text: 'text-status-amber', border: 'border-amber-200' },
  'Aggressive':          { bg: 'bg-status-red-bg',   text: 'text-status-red',   border: 'border-red-200'  },
};

export function IPSSummaryCard({ summary, rm, investorName }: Props) {
  const riskStyle = riskColors[summary.derivedRiskProfile] ??
    { bg: 'bg-gray-50', text: 'text-gray-700', border: 'border-gray-200' };

  return (
    <motion.div
      initial={{ opacity: 0, y: 24 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5, ease: 'easeOut' }}
      className="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden mx-4 mb-4"
    >
      {/* Header */}
      <div className="bg-elara-navy px-5 py-4">
        <div className="flex items-center gap-2">
          <motion.div
            initial={{ scale: 0 }}
            animate={{ scale: 1 }}
            transition={{ type: 'spring', stiffness: 300, delay: 0.2 }}
            className="w-7 h-7 rounded-full bg-status-green flex items-center justify-center flex-shrink-0"
          >
            <span className="text-white text-sm font-bold">✓</span>
          </motion.div>
          <div>
            <p className="text-white font-bold text-sm">Investment Policy Statement</p>
            <p className="text-white/60 text-[11px]">
              {investorName} · Generated by {rm.name} · {rm.firm}
            </p>
          </div>
        </div>
      </div>

      <div className="px-5 py-5 space-y-5">
        {/* Risk profile */}
        <div>
          <p className="text-[10px] font-semibold tracking-widest uppercase text-gray-400 mb-2">
            Risk Profile
          </p>
          <span className={`inline-flex items-center gap-2 px-3 py-1.5 rounded-full border text-sm font-bold ${riskStyle.bg} ${riskStyle.text} ${riskStyle.border}`}>
            <span className="w-2 h-2 rounded-full bg-current opacity-60" />
            {summary.derivedRiskProfile}
          </span>
        </div>

        {/* Goal priority */}
        <div>
          <p className="text-[10px] font-semibold tracking-widest uppercase text-gray-400 mb-2">
            Goal Priority
          </p>
          <div className="space-y-2">
            {summary.derivedGoalPriority.map((goal, i) => (
              <motion.div
                key={goal}
                initial={{ opacity: 0, x: -10 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: 0.1 + i * 0.08 }}
                className="flex items-center gap-3"
              >
                <span className="w-6 h-6 rounded-full bg-elara-navy text-white text-xs font-bold flex items-center justify-center flex-shrink-0">
                  {i + 1}
                </span>
                <span className="text-sm font-medium text-gray-700">{goal}</span>
              </motion.div>
            ))}
          </div>
        </div>

        {/* Values */}
        <div>
          <p className="text-[10px] font-semibold tracking-widest uppercase text-gray-400 mb-2">
            Core Values
          </p>
          <div className="flex flex-wrap gap-2">
            {summary.derivedValues.map((value, i) => (
              <motion.span
                key={value}
                initial={{ opacity: 0, scale: 0.85 }}
                animate={{ opacity: 1, scale: 1 }}
                transition={{ delay: 0.2 + i * 0.06 }}
                className="px-3 py-1 bg-elara-gold/10 border border-elara-gold/30 rounded-full text-xs font-semibold text-elara-navy"
              >
                {value}
              </motion.span>
            ))}
          </div>
        </div>

        {/* Priya's advisor note */}
        {summary.advisorNote && (
          <div>
            <p className="text-[10px] font-semibold tracking-widest uppercase text-gray-400 mb-2">
              Advisor Note
            </p>
            <div className="bg-gray-50 rounded-xl p-4 border-l-3 border-elara-gold relative">
              <div className="flex items-center gap-2 mb-2">
                <div className="relative w-7 h-7 rounded-full overflow-hidden flex-shrink-0 bg-gray-200 ring-1 ring-elara-gold/30">
                  <Image
                    src="/priya-mehta.jpg"
                    alt={rm.name}
                    fill
                    sizes="28px"
                    className="object-cover"
                  />
                </div>
                <p className="text-xs font-semibold text-elara-navy">{rm.name}</p>
                <span className="text-[10px] text-gray-400">· {rm.certification}</span>
              </div>
              <p className="text-xs text-gray-600 leading-relaxed italic">
                &ldquo;{summary.advisorNote}&rdquo;
              </p>
            </div>
          </div>
        )}

        {/* Download IPS button */}
        <motion.button
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.5 }}
          onClick={() => {}}
          className="w-full h-12 bg-elara-navy text-white rounded-xl font-semibold text-sm flex items-center justify-center gap-2 hover:bg-elara-navy-light transition-colors"
        >
          <span>↓</span>
          <span>Download IPS (PDF)</span>
        </motion.button>

        <p className="text-center text-[10px] text-gray-400">
          This IPS is a living document. Priya will review it with you quarterly.
        </p>

        {/* SEBI compliance marker — gives the document legal legitimacy */}
        <div className="border-t border-gray-100 pt-3 text-center space-y-1">
          <p className="text-[10px] text-gray-400 leading-snug">
            Prepared in accordance with SEBI Investment Adviser Regulations, 2013
          </p>
          <p className="text-[10px] text-gray-300">
            Reference: IPS-2026-RKS-001 · Shiv Wealth · SEBI Reg. INA000012487
          </p>
        </div>
      </div>
    </motion.div>
  );
}
